include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.2
APP_NAME = StepChat

StepChat_OBJC_FILES = main.m

ADDITIONAL_LDFLAGS += $(GUI_LIBS) $(FND_LIBS) $(OBJC_LIBS) $(SYSTEM_LIBS)
ADDITIONAL_OBJCFLAGS += -DGNUSTEP -fobjc-arc

include $(GNUSTEP_MAKEFILES)/application.make
